### ISSUE TITLE
Not supported in Firefox 36.0

### ISSUE THREAD

**Issue by davidholtz** [xdamman/selection-sharer#10]
Awesome work here. I don't see a pop up when highlighting in Firefox. Not sure if you tested there or not.

**Comment by kiwimind** [comment]
Using the demo page (http://xdamman.github.io/selection-sharer/lib/selection-sharer/demos/demo.html),  selecting text in Firefox (37.0.2 here), the following error is logged in the console:

`TypeError: selection is undefined`

This is on line 141.

**Comment by kiwimind** [comment]
Apologies, while this doesn't work on the demo page, it _does_ work when using the latest codebase.

Thank you.

**Comment by davidholtz** [comment]
That's great! I can't wait to test it out. Thanks for the reply.
