### ISSUE TITLE
Showing empty space next to icons

### ISSUE THREAD

**Issue by heymartinadams** [xdamman/selection-sharer#38]
See here: http://progressorg.webflow.io/articles/reclaiming-our-land-and-water-michigan-and-the-world

![screenshot](https://cloud.githubusercontent.com/assets/11673745/13199288/954dac0a-d7c5-11e5-8760-78bf013dd30c.jpg)

**Comment by adam-szczombrowski** [comment]
Old issue but I have the same, has someone found a solution for this? @heymartinadams how did you solve this?

**Comment by heymartinadams** [comment]
@adam-szczombrowski not using it anymore.

**Comment by shri3k** [comment]
@adam-szczombrowski It's likely that it's a css issue on your end. Can you try this in this [sandbox](https://jsbin.com/binewuy/1/edit?html,output) and maybe re-create the issue?

**Comment by adam-szczombrowski** [comment]
Hey @shri3k you were right - it was a css issue on my end, solved it already!
